create table concert (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    venue varchar(255) not null,
    description text,
    created_at timestamp with time zone not null default current_timestamp
);

create table concert_schedule (
    id bigint generated by default as identity primary key,
    concert_id bigint not null references concert (id),
    show_at timestamp with time zone not null,
    total_seats integer not null
);

create index idx_concert_schedule_concert_id_show_at
    on concert_schedule (concert_id, show_at);

create table seat (
    id bigint generated by default as identity primary key,
    schedule_id bigint not null references concert_schedule (id),
    seat_number varchar(50) not null,
    price integer not null,
    status varchar(30) not null,
    unique (schedule_id, seat_number)
);

create index idx_seat_schedule_id_status
    on seat (schedule_id, status);

create table reservation (
    id bigint generated by default as identity primary key,
    schedule_id bigint not null references concert_schedule (id),
    seat_id bigint not null unique references seat (id),
    reserver_name varchar(100) not null,
    reservation_status varchar(30) not null,
    reserved_at timestamp with time zone not null default current_timestamp
);

create index idx_reservation_schedule_id_status
    on reservation (schedule_id, reservation_status);
